### ISSUE TITLE
大佬, 建议底层获取get 和post参数的时候加个过滤..使用的时候看了一下,底层貌似是没有加上非法参数过滤...

### ISSUE THREAD

**Issue by shuyabin** [wazsmwazsm/WorkerA#2]
大佬, 建议底层获取get 和post参数的时候加个过滤..使用的时候看了一下,底层貌似是没有加上非法参数过滤...

**Comment by wazsmwazsm** [comment]
@shuyabin 谢谢关注。对于 request 参数过滤的工作我个人建议由用户去做。框架保证数据的原样传输可以给用户更多的操作空间，适用于更多需求、场合。过段时间有空的话我会加入中间件的功能，可以更好的满足你的需求。
