### ISSUE TITLE
可以不用redis么

### ISSUE THREAD

**Issue by foolgry** [wazsmwazsm/WorkerA#5]
就是能不能不要redis，怎么配置下；
直接注释掉redis配置，就报错了。

我看了下代码，默认是有redis的，这里能不能检测下，没有redis配置就不初始化redis了

![image](https://user-images.githubusercontent.com/16127346/78561891-092c4d00-784b-11ea-9193-b3ca93894266.png)

**Comment by wazsmwazsm** [comment]
@foolgry 你好，可以不用的，redis 的配置可以写成如下 
'redis' => [
      'cluster' => FALSE,
      'options' => NULL,
      'rd_con' => [] // 不要任何连接就好
   ]

**Comment by foolgry** [comment]
好的，多谢了
